### PR TITLE
Some Linux buildsystem improvements

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by raptor** [comment]
These look good so far.  Can you give me a reference about games being in man6?  I'm not sure I've ever seen that before.  Is it for a specific distro?

**Comment by akien-mga** [comment]
> Can you give me a reference about games being in man6?

It seems to be the rule on all UNIX-based systems: https://en.wikipedia.org/wiki/Man_page#Manual_sections

**Comment by raptor** [comment]
Thanks!

**Comment by akien-mga** [comment]
You're welcome :) The last issue I can see with the current packaging is that the ``bitfighter_notifier`` does not find its icon as it looks for ``redship48.png`` (likely in its installation directory). But I'll make a PR to add a sed command that changes that on the fly for the path defined as `${CMAKE_DESKTOP_DATA_PATH}/pixmaps/bitfighter.png`.

**Comment by akien-mga** [comment]
BTW, is there a reason why there is no shebang in `bitfighter_notifier.py` but it's added on the fly by the installation instructions?

**Pull request merged**
