### PR TITLE
Clean up Readme and get CI passing

### PR DESCRIPTION
**Pull request by elementc**
# Clean up Readme
The old readme.txt file is full of weird spacing, now-incorrect information, and less-than-professional tone in some places. Replace it with a new markdown readme, which can have pictures, and links, and formatting. Clean up wrong info (old broken links, crufty claims about build system, etc) and delete incomplete or aspirational info (we don't have a good compatibility section, so nuke it).

Add a TravisCI build status icon and some helpful links near the top of the doc for maximum new-contributor-friendliness.

# Get CI Passing
While we have a TravisCI config, it's a little out of date and hasn't passed in a while, so we're not using it.

## Linux Environment
TravisCI was previously configured to build on Ubuntu Trusty, aka Ubuntu 14.04. This 5-year-old-distro is very unsupported- the dependency install step was crashing out on missing packages- and we're building fine (with some new warnings) on Ubuntu as recent as 19.10, so let's just swap in the latest Ubuntu long-term-support release: 18.04 bionic.

## MacOS Dependencies
The dependency install script was failing to remove the boost library because the command to do so had changed. Update the command in the dependency install script.

### CODE REVIEW

**Comment by raptor** [comment]
Hi, and thanks!

We're considering making the 019x branch the master from now on because of several issues.  When I get the switch over complete, would you mind rebasing on the new master?  It may take a day or so.

**Comment by elementc** [comment]
Yeah! Definitely onboard, ping me when you're ready, or I can change to a PR to 19x tonight if you like. Could you elaborate as to the issues / why you'd rather not just merge 019x to master? Treating a release-looking branch as "master" would seem to violate the principle of least astonishment in 2019.

**Comment by eykamp** [comment]
If I understand correctly, master represents a bit of overreach, an ambition that, while grand, will likely never be achieved. It probably should have been undertaken as a branch, but the decision seemed to make sense at the time, when there were two motivated, active devs focused on the project.

We've decided that, for the moment, 019x is the main show, and we're going to restructure to have that become "master" and 020 (what is on master) will become something else.

I hope this will make things less astonishing moving forward.

**Comment by raptor** [comment]
It is done.  The new 'master' branch is the old 'bitfighter-019x' branch and the old 'master' branch is now 'experimental_020'.

@elementc You may now use the **_new_** 'master' :)

**Comment by elementc** [comment]
Hey Chris! I don't know if you remember me, way back in 2008-2010 I was a super eager high schooler wanting to get involved and help with Linux support. Thanks for putting up with me way back when- I'm through college and working at a reusable rocket company on a reasonably-priced satellite internet constellation now, I chalk most of it up to open source projects like bf getting me interested in computer science and talking through how projects evolve. Just wanted to say extra thanks for being so encouraging back then, even though I was way more idea than implementation :)

**Comment by elementc** [comment]
Thanks raptor! I'll rebase here when I get done with some work- late night.

**Comment by eykamp** [comment]
Did you go by ElementC?  I'll just say you're welcome.  We always tried 
to run a positive project, and both raptor and I enjoyed helping folks 
get involved however they could.  For me, the fun was always in the 
helping people take the next step, whatever that was, rather than in the 
playing.

I'm happy things are working out!

Chris

**Comment by elementc** [comment]
Done. The MacOS build bug was fixed in the upgraded master, so I've removed that from the PR description. This should be good for further consideration now.

**Comment by elementc** [comment]
Thanks, I grabbed it from the site :)

**Pull request merged**
