### PR TITLE
Asteroid teams

### PR DESCRIPTION
**Pull request by bobdaduck**
https://bitfighter.org/forums/viewtopic.php?f=4&t=3107

-Asteroid spawns and asteroids now write teams to .level files as an appended "team={teamIndex}" value
-Asteroid Spawns spawn asteroids for their team, and render in that color
-Asteroids display as team's color, black team render as dark grey
-Asteroids are shootable regardless of team, but only damage ships of other teams
-Asteroids collide with ships
-Destroyed size 1 asteroids leave a momentary "shadow", it makes destroying them deeply satisfying
-You can keep a size 1 asteroid with you because it is cute, you can push it around and it won't die unless caught in crossfire, which is ok because asteroids are tribbles
-First foray into a lot of essential code
-Probably needs some cleanup, but is definitely fun
-bobdaduck was here

[teamAsteroidsTestLevel.zip](https://github.com/bitfighter/bitfighter/files/4762985/teamAsteroidsTestLevel.zip)

### CODE REVIEW

**Comment by eykamp** [comment]
This sounds pretty whack, and I will admit that, as usual, I am highly skeptical.  However, it has a few things going for it: 1) It is a clean overlay on top of existing functionality; and 2) it seems mostly (entirely?) coded, which means it's easy to try out, rather than just speculate about, as we usually do. 

It will require a 021 release, which is fine, but maybe we could try it as an undocumented "test" feature.

**Comment by raptor** [comment]
Test features have a nasty habit of becoming permanent. We a small community and no one will want their hard work designing a map with team-asteroids to break in the future. To this day I still get flack for kaen's axing of the Circles object due to bugs and network overload issues.

**Comment by TheSkybax** [comment]
It’s my humble opinion that if the community is behind it then it’s a good call

**Comment by bobdaduck** [comment]
Its pretty obvious that its a feature since it shows in the editor when you change color palettes

I don't think its outrageous enough to change the way the game is played in any fundamental ways, and I did hold off on adding it to the engineer menu :)  but if it was to be accepted we would probably want to commit to it, it would be difficult to hide as a feature

**Pull request merged**
